services:
  database:
    container_name: patient-app-postgres
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: patient-app-user
      POSTGRES_PASSWORD: patient-app-password
      POSTGRES_DB: patient-app-db
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: patient-app-pgadmin
    depends_on:
      - database
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
    driver: local
  pgadmin:
    driver: local
