apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-app-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  rules:
    - host: this-host-will-be-overwritten-in-the-overlays.jonas-blum.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patient-app-backend-service
                port:
                  number: 80
