resources:
  - ../../base
  - namespace.yaml

namespace: patient-app-production

configMapGenerator:
  - name: patient-app-backend-config
    literals:
      - DB_HOST=192.168.1.147
      - DB_PORT=5432
      - DB_NAME=patient_app_production_db
      - DB_USERNAME=therapist-user
      - APP_COOKIE_DOMAIN=jonas-blum.ch
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_PROTOCOL=smtp
      - MAIL_AUTH=true

secretGenerator:
  - name: patient-app-backend-secret
    envs:
      - env.secrets
    type: Opaque

images:
  - name: jonasblum/image-to-be-replaced-depending-on-environment
    newName: jonasblum/patient-app-backend-production
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: patient-app-backend-ingress
    path: patch-ingress.json
