name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-restart:
    runs-on: [self-hosted, k3s]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then

            echo "BRANCH=main" >> $GITHUB_ENV
            echo "BACKEND_IMAGE=jonasblum/patient-app-backend-main:latest" >> $GITHUB_ENV
          fi

      - name: Build Backend Image
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }} .

      - name: Push Backend Image
        run: |
          docker push ${{ env.BACKEND_IMAGE }}

      - name: Restart Kubernetes Deployment
        env:
          DB_PASSWORD_MAIN: ${{ secrets.DB_PASSWORD_MAIN }}
          JWT_SECRET_KEY_MAIN: ${{ secrets.JWT_SECRET_KEY_MAIN }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          LOCAL_AI_API_KEY: ${{secrets.LOCAL_AI_API_KEY}}
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}

        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then


            echo "DB_PASSWORD=$DB_PASSWORD_MAIN" > .kubernetes/overlays/main/env.secrets
            echo "JWT_SECRET_KEY=$JWT_SECRET_KEY_MAIN" >> .kubernetes/overlays/main/env.secrets
            echo "CHATGPT_API_KEY=$CHATGPT_API_KEY" >> .kubernetes/overlays/main/env.secrets
            echo "LOCAL_AI_API_KEY=$LOCAL_AI_API_KEY" >> .kubernetes/overlays/main/env.secrets
            echo "MAIL_USERNAME=$MAIL_USERNAME" >> .kubernetes/overlays/main/env.secrets
            echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .kubernetes/overlays/main/env.secrets

            kubectl apply -k .kubernetes/overlays/main
            kubectl rollout restart deployment/patient-app-backend -n patient-app-main
          fi
